/* 
 * Copyright 2012 Devoteam http://www.devoteam.com
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * 
 * 
 * This file is part of Multi-Protocol Test Suite (MTS).
 * 
 * Multi-Protocol Test Suite (MTS) is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License.
 * 
 * Multi-Protocol Test Suite (MTS) is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Multi-Protocol Test Suite (MTS).
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package com.devoteam.srit.xmlloader.master.master.gui;

/**
 *
 * @author  gege
 */
public class TestLineView extends javax.swing.JPanel {

    /** Creates new form JPanelTest */
    public TestLineView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTestName = new javax.swing.JLabel();
        jButtonReport = new javax.swing.JButton();
        jToggleButtonExpand = new javax.swing.JToggleButton();
        jButtonRun = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jComboBoxRunner = new javax.swing.JComboBox();
        jButtonDeploy = new javax.swing.JButton();
        jButtonXML = new javax.swing.JButton();
        jTextFieldSlave = new javax.swing.JTextField();
        jLabelIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonStop = new javax.swing.JButton();
        jToggleButtonConnect = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(700, 24));
        setLayout(new java.awt.GridBagLayout());

        jLabelTestName.setText("test_name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jLabelTestName, gridBagConstraints);

        jButtonReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/report.png"))); // NOI18N
        jButtonReport.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonReport, gridBagConstraints);

        jToggleButtonExpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/text_list_bullets.png"))); // NOI18N
        jToggleButtonExpand.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jToggleButtonExpand.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jToggleButtonExpand, gridBagConstraints);

        jButtonRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/control_play.png"))); // NOI18N
        jButtonRun.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonRun, gridBagConstraints);

        jProgressBar.setToolTipText("");
        jProgressBar.setValue(50);
        jProgressBar.setMinimumSize(new java.awt.Dimension(146, 17));
        jProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jProgressBar, gridBagConstraints);

        jComboBoxRunner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sequential", "load" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jComboBoxRunner, gridBagConstraints);

        jButtonDeploy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/arrow_refresh_small.png"))); // NOI18N
        jButtonDeploy.setToolTipText("Deploy all tests");
        jButtonDeploy.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonDeploy, gridBagConstraints);

        jButtonXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/script_edit.png"))); // NOI18N
        jButtonXML.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonXML, gridBagConstraints);

        jTextFieldSlave.setText("127.0.0.1:2099");
        jTextFieldSlave.setMargin(new java.awt.Insets(0, 4, 0, 0));
        jTextFieldSlave.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldSlave.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jTextFieldSlave, gridBagConstraints);

        jLabelIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jLabelIcon, gridBagConstraints);

        jLabel1.setText("Slave :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jLabel1, gridBagConstraints);

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/control_stop.png"))); // NOI18N
        jButtonStop.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonStop, gridBagConstraints);

        jToggleButtonConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silk/link_break.png"))); // NOI18N
        jToggleButtonConnect.setMargin(new java.awt.Insets(2, 4, 2, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jToggleButtonConnect, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonDeploy;
    protected javax.swing.JButton jButtonReport;
    protected javax.swing.JButton jButtonRun;
    protected javax.swing.JButton jButtonStop;
    protected javax.swing.JButton jButtonXML;
    protected javax.swing.JComboBox jComboBoxRunner;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabelIcon;
    protected javax.swing.JLabel jLabelTestName;
    protected javax.swing.JProgressBar jProgressBar;
    protected javax.swing.JTextField jTextFieldSlave;
    protected javax.swing.JToggleButton jToggleButtonConnect;
    protected javax.swing.JToggleButton jToggleButtonExpand;
    // End of variables declaration//GEN-END:variables
}
