
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "DisengageRejectReason" )
    public class DisengageRejectReason implements IASN1PreparedElement {
            
        @ASN1Null ( name = "notRegistered" ) 
    
        @ASN1Element ( name = "notRegistered", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject notRegistered = null;
                
  
        @ASN1Null ( name = "requestToDropOther" ) 
    
        @ASN1Element ( name = "requestToDropOther", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject requestToDropOther = null;
                
  
        
        public org.bn.types.NullObject getNotRegistered () {
            return this.notRegistered;
        }

        public boolean isNotRegisteredSelected () {
            return this.notRegistered != null;
        }

        private void setNotRegistered (org.bn.types.NullObject value) {
            this.notRegistered = value;
        }

        
        public void selectNotRegistered () {
            selectNotRegistered (new org.bn.types.NullObject());
	}
	
        public void selectNotRegistered (org.bn.types.NullObject value) {
            this.notRegistered = value;
            
                    setRequestToDropOther(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getRequestToDropOther () {
            return this.requestToDropOther;
        }

        public boolean isRequestToDropOtherSelected () {
            return this.requestToDropOther != null;
        }

        private void setRequestToDropOther (org.bn.types.NullObject value) {
            this.requestToDropOther = value;
        }

        
        public void selectRequestToDropOther () {
            selectRequestToDropOther (new org.bn.types.NullObject());
	}
	
        public void selectRequestToDropOther (org.bn.types.NullObject value) {
            this.requestToDropOther = value;
            
                    setNotRegistered(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DisengageRejectReason.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            