
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "H323_UserInformation", isSet = false )
    public class H323_UserInformation implements IASN1PreparedElement {
            
        @ASN1Element ( name = "h323-uu-pdu", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H323_UU_PDU h323_uu_pdu = null;
                
  

       @ASN1PreparedElement
       @ASN1Sequence ( name = "user-data" , isSet = false )
       public static class User_dataSequenceType implements IASN1PreparedElement {
                @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 255L 
		
	   )
	   
        @ASN1Element ( name = "protocol-discriminator", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer protocol_discriminator = null;
                
  @ASN1OctetString( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 131L 
		
	   )
	   
        @ASN1Element ( name = "user-information", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] user_information = null;
                
  
        
        public Integer getProtocol_discriminator () {
            return this.protocol_discriminator;
        }

        

        public void setProtocol_discriminator (Integer value) {
            this.protocol_discriminator = value;
        }
        
  
        
        public byte[] getUser_information () {
            return this.user_information;
        }

        

        public void setUser_information (byte[] value) {
            this.user_information = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_User_dataSequenceType;
        }

       private static IASN1PreparedElementData preparedData_User_dataSequenceType = CoderFactory.getInstance().newPreparedElementData(User_dataSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "user-data", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private User_dataSequenceType user_data = null;
                
  
        
        public H323_UU_PDU getH323_uu_pdu () {
            return this.h323_uu_pdu;
        }

        

        public void setH323_uu_pdu (H323_UU_PDU value) {
            this.h323_uu_pdu = value;
        }
        
  
        
        public User_dataSequenceType getUser_data () {
            return this.user_data;
        }

        
        public boolean isUser_dataPresent () {
            return this.user_data != null;
        }
        

        public void setUser_data (User_dataSequenceType value) {
            this.user_data = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(H323_UserInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            