
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "LocationConfirm", isSet = false )
    public class LocationConfirm implements IASN1PreparedElement {
            
        @ASN1Element ( name = "requestSeqNum", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RequestSeqNum requestSeqNum = null;
                
  
        @ASN1Element ( name = "callSignalAddress", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TransportAddress callSignalAddress = null;
                
  
        @ASN1Element ( name = "rasAddress", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TransportAddress rasAddress = null;
                
  
        @ASN1Element ( name = "nonStandardData", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardParameter nonStandardData = null;
                
  
        
        public RequestSeqNum getRequestSeqNum () {
            return this.requestSeqNum;
        }

        

        public void setRequestSeqNum (RequestSeqNum value) {
            this.requestSeqNum = value;
        }
        
  
        
        public TransportAddress getCallSignalAddress () {
            return this.callSignalAddress;
        }

        

        public void setCallSignalAddress (TransportAddress value) {
            this.callSignalAddress = value;
        }
        
  
        
        public TransportAddress getRasAddress () {
            return this.rasAddress;
        }

        

        public void setRasAddress (TransportAddress value) {
            this.rasAddress = value;
        }
        
  
        
        public NonStandardParameter getNonStandardData () {
            return this.nonStandardData;
        }

        
        public boolean isNonStandardDataPresent () {
            return this.nonStandardData != null;
        }
        

        public void setNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(LocationConfirm.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            