
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "FacilityReason" )
    public class FacilityReason implements IASN1PreparedElement {
            
        @ASN1Null ( name = "routeCallToGatekeeper" ) 
    
        @ASN1Element ( name = "routeCallToGatekeeper", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject routeCallToGatekeeper = null;
                
  
        @ASN1Null ( name = "callForwarded" ) 
    
        @ASN1Element ( name = "callForwarded", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject callForwarded = null;
                
  
        @ASN1Null ( name = "routeCallToMC" ) 
    
        @ASN1Element ( name = "routeCallToMC", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject routeCallToMC = null;
                
  
        @ASN1Null ( name = "undefinedReason" ) 
    
        @ASN1Element ( name = "undefinedReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject undefinedReason = null;
                
  
        
        public org.bn.types.NullObject getRouteCallToGatekeeper () {
            return this.routeCallToGatekeeper;
        }

        public boolean isRouteCallToGatekeeperSelected () {
            return this.routeCallToGatekeeper != null;
        }

        private void setRouteCallToGatekeeper (org.bn.types.NullObject value) {
            this.routeCallToGatekeeper = value;
        }

        
        public void selectRouteCallToGatekeeper () {
            selectRouteCallToGatekeeper (new org.bn.types.NullObject());
	}
	
        public void selectRouteCallToGatekeeper (org.bn.types.NullObject value) {
            this.routeCallToGatekeeper = value;
            
                    setCallForwarded(null);
                
                    setRouteCallToMC(null);
                
                    setUndefinedReason(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getCallForwarded () {
            return this.callForwarded;
        }

        public boolean isCallForwardedSelected () {
            return this.callForwarded != null;
        }

        private void setCallForwarded (org.bn.types.NullObject value) {
            this.callForwarded = value;
        }

        
        public void selectCallForwarded () {
            selectCallForwarded (new org.bn.types.NullObject());
	}
	
        public void selectCallForwarded (org.bn.types.NullObject value) {
            this.callForwarded = value;
            
                    setRouteCallToGatekeeper(null);
                
                    setRouteCallToMC(null);
                
                    setUndefinedReason(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getRouteCallToMC () {
            return this.routeCallToMC;
        }

        public boolean isRouteCallToMCSelected () {
            return this.routeCallToMC != null;
        }

        private void setRouteCallToMC (org.bn.types.NullObject value) {
            this.routeCallToMC = value;
        }

        
        public void selectRouteCallToMC () {
            selectRouteCallToMC (new org.bn.types.NullObject());
	}
	
        public void selectRouteCallToMC (org.bn.types.NullObject value) {
            this.routeCallToMC = value;
            
                    setRouteCallToGatekeeper(null);
                
                    setCallForwarded(null);
                
                    setUndefinedReason(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUndefinedReason () {
            return this.undefinedReason;
        }

        public boolean isUndefinedReasonSelected () {
            return this.undefinedReason != null;
        }

        private void setUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
        }

        
        public void selectUndefinedReason () {
            selectUndefinedReason (new org.bn.types.NullObject());
	}
	
        public void selectUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
            
                    setRouteCallToGatekeeper(null);
                
                    setCallForwarded(null);
                
                    setRouteCallToMC(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(FacilityReason.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            