
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GatekeeperReject", isSet = false )
    public class GatekeeperReject implements IASN1PreparedElement {
            
        @ASN1Element ( name = "requestSeqNum", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RequestSeqNum requestSeqNum = null;
                
  
        @ASN1Element ( name = "protocolIdentifier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ProtocolIdentifier protocolIdentifier = null;
                
  
        @ASN1Element ( name = "nonStandardData", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardParameter nonStandardData = null;
                
  
        @ASN1Element ( name = "gatekeeperIdentifier", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GatekeeperIdentifier gatekeeperIdentifier = null;
                
  
        @ASN1Element ( name = "rejectReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GatekeeperRejectReason rejectReason = null;
                
  
        
        public RequestSeqNum getRequestSeqNum () {
            return this.requestSeqNum;
        }

        

        public void setRequestSeqNum (RequestSeqNum value) {
            this.requestSeqNum = value;
        }
        
  
        
        public ProtocolIdentifier getProtocolIdentifier () {
            return this.protocolIdentifier;
        }

        

        public void setProtocolIdentifier (ProtocolIdentifier value) {
            this.protocolIdentifier = value;
        }
        
  
        
        public NonStandardParameter getNonStandardData () {
            return this.nonStandardData;
        }

        
        public boolean isNonStandardDataPresent () {
            return this.nonStandardData != null;
        }
        

        public void setNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
        }
        
  
        
        public GatekeeperIdentifier getGatekeeperIdentifier () {
            return this.gatekeeperIdentifier;
        }

        
        public boolean isGatekeeperIdentifierPresent () {
            return this.gatekeeperIdentifier != null;
        }
        

        public void setGatekeeperIdentifier (GatekeeperIdentifier value) {
            this.gatekeeperIdentifier = value;
        }
        
  
        
        public GatekeeperRejectReason getRejectReason () {
            return this.rejectReason;
        }

        

        public void setRejectReason (GatekeeperRejectReason value) {
            this.rejectReason = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GatekeeperReject.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            