
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "InfoRequest", isSet = false )
    public class InfoRequest implements IASN1PreparedElement {
            
        @ASN1Element ( name = "requestSeqNum", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RequestSeqNum requestSeqNum = null;
                
  
        @ASN1Element ( name = "callReferenceValue", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CallReferenceValue callReferenceValue = null;
                
  
        @ASN1Element ( name = "nonStandardData", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardParameter nonStandardData = null;
                
  
        @ASN1Element ( name = "replyAddress", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TransportAddress replyAddress = null;
                
  
        
        public RequestSeqNum getRequestSeqNum () {
            return this.requestSeqNum;
        }

        

        public void setRequestSeqNum (RequestSeqNum value) {
            this.requestSeqNum = value;
        }
        
  
        
        public CallReferenceValue getCallReferenceValue () {
            return this.callReferenceValue;
        }

        

        public void setCallReferenceValue (CallReferenceValue value) {
            this.callReferenceValue = value;
        }
        
  
        
        public NonStandardParameter getNonStandardData () {
            return this.nonStandardData;
        }

        
        public boolean isNonStandardDataPresent () {
            return this.nonStandardData != null;
        }
        

        public void setNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
        }
        
  
        
        public TransportAddress getReplyAddress () {
            return this.replyAddress;
        }

        
        public boolean isReplyAddressPresent () {
            return this.replyAddress != null;
        }
        

        public void setReplyAddress (TransportAddress value) {
            this.replyAddress = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InfoRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            