
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DisengageRequest", isSet = false )
    public class DisengageRequest implements IASN1PreparedElement {
            
        @ASN1Element ( name = "requestSeqNum", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RequestSeqNum requestSeqNum = null;
                
  
        @ASN1Element ( name = "endpointIdentifier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EndpointIdentifier endpointIdentifier = null;
                
  
        @ASN1Element ( name = "conferenceID", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ConferenceIdentifier conferenceID = null;
                
  
        @ASN1Element ( name = "callReferenceValue", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CallReferenceValue callReferenceValue = null;
                
  
        @ASN1Element ( name = "disengageReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DisengageReason disengageReason = null;
                
  
        @ASN1Element ( name = "nonStandardData", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardParameter nonStandardData = null;
                
  
        
        public RequestSeqNum getRequestSeqNum () {
            return this.requestSeqNum;
        }

        

        public void setRequestSeqNum (RequestSeqNum value) {
            this.requestSeqNum = value;
        }
        
  
        
        public EndpointIdentifier getEndpointIdentifier () {
            return this.endpointIdentifier;
        }

        

        public void setEndpointIdentifier (EndpointIdentifier value) {
            this.endpointIdentifier = value;
        }
        
  
        
        public ConferenceIdentifier getConferenceID () {
            return this.conferenceID;
        }

        

        public void setConferenceID (ConferenceIdentifier value) {
            this.conferenceID = value;
        }
        
  
        
        public CallReferenceValue getCallReferenceValue () {
            return this.callReferenceValue;
        }

        

        public void setCallReferenceValue (CallReferenceValue value) {
            this.callReferenceValue = value;
        }
        
  
        
        public DisengageReason getDisengageReason () {
            return this.disengageReason;
        }

        

        public void setDisengageReason (DisengageReason value) {
            this.disengageReason = value;
        }
        
  
        
        public NonStandardParameter getNonStandardData () {
            return this.nonStandardData;
        }

        
        public boolean isNonStandardDataPresent () {
            return this.nonStandardData != null;
        }
        

        public void setNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DisengageRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            