
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Q954Details", isSet = false )
    public class Q954Details implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "conferenceCalling", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean conferenceCalling = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "threePartyService", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean threePartyService = null;
                
  
        
        public Boolean getConferenceCalling () {
            return this.conferenceCalling;
        }

        

        public void setConferenceCalling (Boolean value) {
            this.conferenceCalling = value;
        }
        
  
        
        public Boolean getThreePartyService () {
            return this.threePartyService;
        }

        

        public void setThreePartyService (Boolean value) {
            this.threePartyService = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Q954Details.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            