
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "QseriesOptions", isSet = false )
    public class QseriesOptions implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q932Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q932Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q951Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q951Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q952Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q952Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q953Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q953Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q955Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q955Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q956Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q956Full = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "q957Full", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean q957Full = null;
                
  
        @ASN1Element ( name = "q954Info", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Q954Details q954Info = null;
                
  
        
        public Boolean getQ932Full () {
            return this.q932Full;
        }

        

        public void setQ932Full (Boolean value) {
            this.q932Full = value;
        }
        
  
        
        public Boolean getQ951Full () {
            return this.q951Full;
        }

        

        public void setQ951Full (Boolean value) {
            this.q951Full = value;
        }
        
  
        
        public Boolean getQ952Full () {
            return this.q952Full;
        }

        

        public void setQ952Full (Boolean value) {
            this.q952Full = value;
        }
        
  
        
        public Boolean getQ953Full () {
            return this.q953Full;
        }

        

        public void setQ953Full (Boolean value) {
            this.q953Full = value;
        }
        
  
        
        public Boolean getQ955Full () {
            return this.q955Full;
        }

        

        public void setQ955Full (Boolean value) {
            this.q955Full = value;
        }
        
  
        
        public Boolean getQ956Full () {
            return this.q956Full;
        }

        

        public void setQ956Full (Boolean value) {
            this.q956Full = value;
        }
        
  
        
        public Boolean getQ957Full () {
            return this.q957Full;
        }

        

        public void setQ957Full (Boolean value) {
            this.q957Full = value;
        }
        
  
        
        public Q954Details getQ954Info () {
            return this.q954Info;
        }

        

        public void setQ954Info (Q954Details value) {
            this.q954Info = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(QseriesOptions.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            