
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "RasMessage" )
    public class RasMessage implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gatekeeperRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GatekeeperRequest gatekeeperRequest = null;
                
  
        @ASN1Element ( name = "gatekeeperConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GatekeeperConfirm gatekeeperConfirm = null;
                
  
        @ASN1Element ( name = "gatekeeperReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private GatekeeperReject gatekeeperReject = null;
                
  
        @ASN1Element ( name = "registrationRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RegistrationRequest registrationRequest = null;
                
  
        @ASN1Element ( name = "registrationConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RegistrationConfirm registrationConfirm = null;
                
  
        @ASN1Element ( name = "registrationReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RegistrationReject registrationReject = null;
                
  
        @ASN1Element ( name = "unregistrationRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UnregistrationRequest unregistrationRequest = null;
                
  
        @ASN1Element ( name = "unregistrationConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UnregistrationConfirm unregistrationConfirm = null;
                
  
        @ASN1Element ( name = "unregistrationReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UnregistrationReject unregistrationReject = null;
                
  
        @ASN1Element ( name = "admissionRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AdmissionRequest admissionRequest = null;
                
  
        @ASN1Element ( name = "admissionConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AdmissionConfirm admissionConfirm = null;
                
  
        @ASN1Element ( name = "admissionReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AdmissionReject admissionReject = null;
                
  
        @ASN1Element ( name = "bandwidthRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BandwidthRequest bandwidthRequest = null;
                
  
        @ASN1Element ( name = "bandwidthConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BandwidthConfirm bandwidthConfirm = null;
                
  
        @ASN1Element ( name = "bandwidthReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BandwidthReject bandwidthReject = null;
                
  
        @ASN1Element ( name = "disengageRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DisengageRequest disengageRequest = null;
                
  
        @ASN1Element ( name = "disengageConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DisengageConfirm disengageConfirm = null;
                
  
        @ASN1Element ( name = "disengageReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DisengageReject disengageReject = null;
                
  
        @ASN1Element ( name = "locationRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocationRequest locationRequest = null;
                
  
        @ASN1Element ( name = "locationConfirm", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocationConfirm locationConfirm = null;
                
  
        @ASN1Element ( name = "locationReject", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private LocationReject locationReject = null;
                
  
        @ASN1Element ( name = "infoRequest", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InfoRequest infoRequest = null;
                
  
        @ASN1Element ( name = "infoRequestResponse", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InfoRequestResponse infoRequestResponse = null;
                
  
        @ASN1Element ( name = "nonStandardMessage", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardMessage nonStandardMessage = null;
                
  
        @ASN1Element ( name = "unknownMessageResponse", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UnknownMessageResponse unknownMessageResponse = null;
                
  
        
        public GatekeeperRequest getGatekeeperRequest () {
            return this.gatekeeperRequest;
        }

        public boolean isGatekeeperRequestSelected () {
            return this.gatekeeperRequest != null;
        }

        private void setGatekeeperRequest (GatekeeperRequest value) {
            this.gatekeeperRequest = value;
        }

        
        public void selectGatekeeperRequest (GatekeeperRequest value) {
            this.gatekeeperRequest = value;
            
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public GatekeeperConfirm getGatekeeperConfirm () {
            return this.gatekeeperConfirm;
        }

        public boolean isGatekeeperConfirmSelected () {
            return this.gatekeeperConfirm != null;
        }

        private void setGatekeeperConfirm (GatekeeperConfirm value) {
            this.gatekeeperConfirm = value;
        }

        
        public void selectGatekeeperConfirm (GatekeeperConfirm value) {
            this.gatekeeperConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public GatekeeperReject getGatekeeperReject () {
            return this.gatekeeperReject;
        }

        public boolean isGatekeeperRejectSelected () {
            return this.gatekeeperReject != null;
        }

        private void setGatekeeperReject (GatekeeperReject value) {
            this.gatekeeperReject = value;
        }

        
        public void selectGatekeeperReject (GatekeeperReject value) {
            this.gatekeeperReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public RegistrationRequest getRegistrationRequest () {
            return this.registrationRequest;
        }

        public boolean isRegistrationRequestSelected () {
            return this.registrationRequest != null;
        }

        private void setRegistrationRequest (RegistrationRequest value) {
            this.registrationRequest = value;
        }

        
        public void selectRegistrationRequest (RegistrationRequest value) {
            this.registrationRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public RegistrationConfirm getRegistrationConfirm () {
            return this.registrationConfirm;
        }

        public boolean isRegistrationConfirmSelected () {
            return this.registrationConfirm != null;
        }

        private void setRegistrationConfirm (RegistrationConfirm value) {
            this.registrationConfirm = value;
        }

        
        public void selectRegistrationConfirm (RegistrationConfirm value) {
            this.registrationConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public RegistrationReject getRegistrationReject () {
            return this.registrationReject;
        }

        public boolean isRegistrationRejectSelected () {
            return this.registrationReject != null;
        }

        private void setRegistrationReject (RegistrationReject value) {
            this.registrationReject = value;
        }

        
        public void selectRegistrationReject (RegistrationReject value) {
            this.registrationReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public UnregistrationRequest getUnregistrationRequest () {
            return this.unregistrationRequest;
        }

        public boolean isUnregistrationRequestSelected () {
            return this.unregistrationRequest != null;
        }

        private void setUnregistrationRequest (UnregistrationRequest value) {
            this.unregistrationRequest = value;
        }

        
        public void selectUnregistrationRequest (UnregistrationRequest value) {
            this.unregistrationRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public UnregistrationConfirm getUnregistrationConfirm () {
            return this.unregistrationConfirm;
        }

        public boolean isUnregistrationConfirmSelected () {
            return this.unregistrationConfirm != null;
        }

        private void setUnregistrationConfirm (UnregistrationConfirm value) {
            this.unregistrationConfirm = value;
        }

        
        public void selectUnregistrationConfirm (UnregistrationConfirm value) {
            this.unregistrationConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public UnregistrationReject getUnregistrationReject () {
            return this.unregistrationReject;
        }

        public boolean isUnregistrationRejectSelected () {
            return this.unregistrationReject != null;
        }

        private void setUnregistrationReject (UnregistrationReject value) {
            this.unregistrationReject = value;
        }

        
        public void selectUnregistrationReject (UnregistrationReject value) {
            this.unregistrationReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public AdmissionRequest getAdmissionRequest () {
            return this.admissionRequest;
        }

        public boolean isAdmissionRequestSelected () {
            return this.admissionRequest != null;
        }

        private void setAdmissionRequest (AdmissionRequest value) {
            this.admissionRequest = value;
        }

        
        public void selectAdmissionRequest (AdmissionRequest value) {
            this.admissionRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public AdmissionConfirm getAdmissionConfirm () {
            return this.admissionConfirm;
        }

        public boolean isAdmissionConfirmSelected () {
            return this.admissionConfirm != null;
        }

        private void setAdmissionConfirm (AdmissionConfirm value) {
            this.admissionConfirm = value;
        }

        
        public void selectAdmissionConfirm (AdmissionConfirm value) {
            this.admissionConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public AdmissionReject getAdmissionReject () {
            return this.admissionReject;
        }

        public boolean isAdmissionRejectSelected () {
            return this.admissionReject != null;
        }

        private void setAdmissionReject (AdmissionReject value) {
            this.admissionReject = value;
        }

        
        public void selectAdmissionReject (AdmissionReject value) {
            this.admissionReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public BandwidthRequest getBandwidthRequest () {
            return this.bandwidthRequest;
        }

        public boolean isBandwidthRequestSelected () {
            return this.bandwidthRequest != null;
        }

        private void setBandwidthRequest (BandwidthRequest value) {
            this.bandwidthRequest = value;
        }

        
        public void selectBandwidthRequest (BandwidthRequest value) {
            this.bandwidthRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public BandwidthConfirm getBandwidthConfirm () {
            return this.bandwidthConfirm;
        }

        public boolean isBandwidthConfirmSelected () {
            return this.bandwidthConfirm != null;
        }

        private void setBandwidthConfirm (BandwidthConfirm value) {
            this.bandwidthConfirm = value;
        }

        
        public void selectBandwidthConfirm (BandwidthConfirm value) {
            this.bandwidthConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public BandwidthReject getBandwidthReject () {
            return this.bandwidthReject;
        }

        public boolean isBandwidthRejectSelected () {
            return this.bandwidthReject != null;
        }

        private void setBandwidthReject (BandwidthReject value) {
            this.bandwidthReject = value;
        }

        
        public void selectBandwidthReject (BandwidthReject value) {
            this.bandwidthReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public DisengageRequest getDisengageRequest () {
            return this.disengageRequest;
        }

        public boolean isDisengageRequestSelected () {
            return this.disengageRequest != null;
        }

        private void setDisengageRequest (DisengageRequest value) {
            this.disengageRequest = value;
        }

        
        public void selectDisengageRequest (DisengageRequest value) {
            this.disengageRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public DisengageConfirm getDisengageConfirm () {
            return this.disengageConfirm;
        }

        public boolean isDisengageConfirmSelected () {
            return this.disengageConfirm != null;
        }

        private void setDisengageConfirm (DisengageConfirm value) {
            this.disengageConfirm = value;
        }

        
        public void selectDisengageConfirm (DisengageConfirm value) {
            this.disengageConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public DisengageReject getDisengageReject () {
            return this.disengageReject;
        }

        public boolean isDisengageRejectSelected () {
            return this.disengageReject != null;
        }

        private void setDisengageReject (DisengageReject value) {
            this.disengageReject = value;
        }

        
        public void selectDisengageReject (DisengageReject value) {
            this.disengageReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public LocationRequest getLocationRequest () {
            return this.locationRequest;
        }

        public boolean isLocationRequestSelected () {
            return this.locationRequest != null;
        }

        private void setLocationRequest (LocationRequest value) {
            this.locationRequest = value;
        }

        
        public void selectLocationRequest (LocationRequest value) {
            this.locationRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public LocationConfirm getLocationConfirm () {
            return this.locationConfirm;
        }

        public boolean isLocationConfirmSelected () {
            return this.locationConfirm != null;
        }

        private void setLocationConfirm (LocationConfirm value) {
            this.locationConfirm = value;
        }

        
        public void selectLocationConfirm (LocationConfirm value) {
            this.locationConfirm = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public LocationReject getLocationReject () {
            return this.locationReject;
        }

        public boolean isLocationRejectSelected () {
            return this.locationReject != null;
        }

        private void setLocationReject (LocationReject value) {
            this.locationReject = value;
        }

        
        public void selectLocationReject (LocationReject value) {
            this.locationReject = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public InfoRequest getInfoRequest () {
            return this.infoRequest;
        }

        public boolean isInfoRequestSelected () {
            return this.infoRequest != null;
        }

        private void setInfoRequest (InfoRequest value) {
            this.infoRequest = value;
        }

        
        public void selectInfoRequest (InfoRequest value) {
            this.infoRequest = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public InfoRequestResponse getInfoRequestResponse () {
            return this.infoRequestResponse;
        }

        public boolean isInfoRequestResponseSelected () {
            return this.infoRequestResponse != null;
        }

        private void setInfoRequestResponse (InfoRequestResponse value) {
            this.infoRequestResponse = value;
        }

        
        public void selectInfoRequestResponse (InfoRequestResponse value) {
            this.infoRequestResponse = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setNonStandardMessage(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public NonStandardMessage getNonStandardMessage () {
            return this.nonStandardMessage;
        }

        public boolean isNonStandardMessageSelected () {
            return this.nonStandardMessage != null;
        }

        private void setNonStandardMessage (NonStandardMessage value) {
            this.nonStandardMessage = value;
        }

        
        public void selectNonStandardMessage (NonStandardMessage value) {
            this.nonStandardMessage = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setUnknownMessageResponse(null);
                            
        }

        
  
        
        public UnknownMessageResponse getUnknownMessageResponse () {
            return this.unknownMessageResponse;
        }

        public boolean isUnknownMessageResponseSelected () {
            return this.unknownMessageResponse != null;
        }

        private void setUnknownMessageResponse (UnknownMessageResponse value) {
            this.unknownMessageResponse = value;
        }

        
        public void selectUnknownMessageResponse (UnknownMessageResponse value) {
            this.unknownMessageResponse = value;
            
                    setGatekeeperRequest(null);
                
                    setGatekeeperConfirm(null);
                
                    setGatekeeperReject(null);
                
                    setRegistrationRequest(null);
                
                    setRegistrationConfirm(null);
                
                    setRegistrationReject(null);
                
                    setUnregistrationRequest(null);
                
                    setUnregistrationConfirm(null);
                
                    setUnregistrationReject(null);
                
                    setAdmissionRequest(null);
                
                    setAdmissionConfirm(null);
                
                    setAdmissionReject(null);
                
                    setBandwidthRequest(null);
                
                    setBandwidthConfirm(null);
                
                    setBandwidthReject(null);
                
                    setDisengageRequest(null);
                
                    setDisengageConfirm(null);
                
                    setDisengageReject(null);
                
                    setLocationRequest(null);
                
                    setLocationConfirm(null);
                
                    setLocationReject(null);
                
                    setInfoRequest(null);
                
                    setInfoRequestResponse(null);
                
                    setNonStandardMessage(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RasMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            