
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ReleaseComplete_UUIE", isSet = false )
    public class ReleaseComplete_UUIE implements IASN1PreparedElement {
            
        @ASN1Element ( name = "protocolIdentifier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ProtocolIdentifier protocolIdentifier = null;
                
  
        @ASN1Element ( name = "reason", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ReleaseCompleteReason reason = null;
                
  
        
        public ProtocolIdentifier getProtocolIdentifier () {
            return this.protocolIdentifier;
        }

        

        public void setProtocolIdentifier (ProtocolIdentifier value) {
            this.protocolIdentifier = value;
        }
        
  
        
        public ReleaseCompleteReason getReason () {
            return this.reason;
        }

        
        public boolean isReasonPresent () {
            return this.reason != null;
        }
        

        public void setReason (ReleaseCompleteReason value) {
            this.reason = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ReleaseComplete_UUIE.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            