/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Line.java
 *
 * Created on 11 nov. 2011, 19:43:44
 */
package com.devoteam.srit.xmlloader.master.master.gui;

/**
 *
 * @author Gwenhael
 */
public class TestcaseLineView extends javax.swing.JPanel {

    /** Creates new form Line */
    public TestcaseLineView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBoxSelected = new javax.swing.JCheckBox();
        jProgressBar = new javax.swing.JProgressBar();
        jLabelIcon = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jCheckBoxSelected.setText("Testcase description or name");
        jCheckBoxSelected.setEnabled(false);
        jCheckBoxSelected.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jCheckBoxSelected, gridBagConstraints);

        jProgressBar.setValue(35);
        jProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jProgressBar, gridBagConstraints);

        jLabelIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jLabelIcon, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox jCheckBoxSelected;
    protected javax.swing.JLabel jLabelIcon;
    protected javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
