
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "SupportedProtocols" )
    public class SupportedProtocols implements IASN1PreparedElement {
            
        @ASN1Element ( name = "nonStandardData", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonStandardParameter nonStandardData = null;
                
  
        @ASN1Element ( name = "h310", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H310Caps h310 = null;
                
  
        @ASN1Element ( name = "h320", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H320Caps h320 = null;
                
  
        @ASN1Element ( name = "h321", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H321Caps h321 = null;
                
  
        @ASN1Element ( name = "h322", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H322Caps h322 = null;
                
  
        @ASN1Element ( name = "h323", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H323Caps h323 = null;
                
  
        @ASN1Element ( name = "h324", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private H324Caps h324 = null;
                
  
        @ASN1Element ( name = "voice", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private VoiceCaps voice = null;
                
  
        @ASN1Element ( name = "t120-only", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private T120OnlyCaps t120_only = null;
                
  
        
        public NonStandardParameter getNonStandardData () {
            return this.nonStandardData;
        }

        public boolean isNonStandardDataSelected () {
            return this.nonStandardData != null;
        }

        private void setNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
        }

        
        public void selectNonStandardData (NonStandardParameter value) {
            this.nonStandardData = value;
            
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H310Caps getH310 () {
            return this.h310;
        }

        public boolean isH310Selected () {
            return this.h310 != null;
        }

        private void setH310 (H310Caps value) {
            this.h310 = value;
        }

        
        public void selectH310 (H310Caps value) {
            this.h310 = value;
            
                    setNonStandardData(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H320Caps getH320 () {
            return this.h320;
        }

        public boolean isH320Selected () {
            return this.h320 != null;
        }

        private void setH320 (H320Caps value) {
            this.h320 = value;
        }

        
        public void selectH320 (H320Caps value) {
            this.h320 = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H321Caps getH321 () {
            return this.h321;
        }

        public boolean isH321Selected () {
            return this.h321 != null;
        }

        private void setH321 (H321Caps value) {
            this.h321 = value;
        }

        
        public void selectH321 (H321Caps value) {
            this.h321 = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H322Caps getH322 () {
            return this.h322;
        }

        public boolean isH322Selected () {
            return this.h322 != null;
        }

        private void setH322 (H322Caps value) {
            this.h322 = value;
        }

        
        public void selectH322 (H322Caps value) {
            this.h322 = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H323Caps getH323 () {
            return this.h323;
        }

        public boolean isH323Selected () {
            return this.h323 != null;
        }

        private void setH323 (H323Caps value) {
            this.h323 = value;
        }

        
        public void selectH323 (H323Caps value) {
            this.h323 = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH324(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public H324Caps getH324 () {
            return this.h324;
        }

        public boolean isH324Selected () {
            return this.h324 != null;
        }

        private void setH324 (H324Caps value) {
            this.h324 = value;
        }

        
        public void selectH324 (H324Caps value) {
            this.h324 = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setVoice(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public VoiceCaps getVoice () {
            return this.voice;
        }

        public boolean isVoiceSelected () {
            return this.voice != null;
        }

        private void setVoice (VoiceCaps value) {
            this.voice = value;
        }

        
        public void selectVoice (VoiceCaps value) {
            this.voice = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setT120_only(null);
                            
        }

        
  
        
        public T120OnlyCaps getT120_only () {
            return this.t120_only;
        }

        public boolean isT120_onlySelected () {
            return this.t120_only != null;
        }

        private void setT120_only (T120OnlyCaps value) {
            this.t120_only = value;
        }

        
        public void selectT120_only (T120OnlyCaps value) {
            this.t120_only = value;
            
                    setNonStandardData(null);
                
                    setH310(null);
                
                    setH320(null);
                
                    setH321(null);
                
                    setH322(null);
                
                    setH323(null);
                
                    setH324(null);
                
                    setVoice(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SupportedProtocols.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            