
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TransportChannelInfo", isSet = false )
    public class TransportChannelInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "sendAddress", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TransportAddress sendAddress = null;
                
  
        @ASN1Element ( name = "recvAddress", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private TransportAddress recvAddress = null;
                
  
        
        public TransportAddress getSendAddress () {
            return this.sendAddress;
        }

        
        public boolean isSendAddressPresent () {
            return this.sendAddress != null;
        }
        

        public void setSendAddress (TransportAddress value) {
            this.sendAddress = value;
        }
        
  
        
        public TransportAddress getRecvAddress () {
            return this.recvAddress;
        }

        
        public boolean isRecvAddressPresent () {
            return this.recvAddress != null;
        }
        

        public void setRecvAddress (TransportAddress value) {
            this.recvAddress = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TransportChannelInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            