
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "AdmissionRejectReason" )
    public class AdmissionRejectReason implements IASN1PreparedElement {
            
        @ASN1Null ( name = "calledPartyNotRegistered" ) 
    
        @ASN1Element ( name = "calledPartyNotRegistered", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject calledPartyNotRegistered = null;
                
  
        @ASN1Null ( name = "invalidPermission" ) 
    
        @ASN1Element ( name = "invalidPermission", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject invalidPermission = null;
                
  
        @ASN1Null ( name = "requestDenied" ) 
    
        @ASN1Element ( name = "requestDenied", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject requestDenied = null;
                
  
        @ASN1Null ( name = "undefinedReason" ) 
    
        @ASN1Element ( name = "undefinedReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject undefinedReason = null;
                
  
        @ASN1Null ( name = "callerNotRegistered" ) 
    
        @ASN1Element ( name = "callerNotRegistered", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject callerNotRegistered = null;
                
  
        @ASN1Null ( name = "routeCallToGatekeeper" ) 
    
        @ASN1Element ( name = "routeCallToGatekeeper", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject routeCallToGatekeeper = null;
                
  
        @ASN1Null ( name = "invalidEndpointIdentifier" ) 
    
        @ASN1Element ( name = "invalidEndpointIdentifier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject invalidEndpointIdentifier = null;
                
  
        @ASN1Null ( name = "resourceUnavailable" ) 
    
        @ASN1Element ( name = "resourceUnavailable", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject resourceUnavailable = null;
                
  
        
        public org.bn.types.NullObject getCalledPartyNotRegistered () {
            return this.calledPartyNotRegistered;
        }

        public boolean isCalledPartyNotRegisteredSelected () {
            return this.calledPartyNotRegistered != null;
        }

        private void setCalledPartyNotRegistered (org.bn.types.NullObject value) {
            this.calledPartyNotRegistered = value;
        }

        
        public void selectCalledPartyNotRegistered () {
            selectCalledPartyNotRegistered (new org.bn.types.NullObject());
	}
	
        public void selectCalledPartyNotRegistered (org.bn.types.NullObject value) {
            this.calledPartyNotRegistered = value;
            
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getInvalidPermission () {
            return this.invalidPermission;
        }

        public boolean isInvalidPermissionSelected () {
            return this.invalidPermission != null;
        }

        private void setInvalidPermission (org.bn.types.NullObject value) {
            this.invalidPermission = value;
        }

        
        public void selectInvalidPermission () {
            selectInvalidPermission (new org.bn.types.NullObject());
	}
	
        public void selectInvalidPermission (org.bn.types.NullObject value) {
            this.invalidPermission = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getRequestDenied () {
            return this.requestDenied;
        }

        public boolean isRequestDeniedSelected () {
            return this.requestDenied != null;
        }

        private void setRequestDenied (org.bn.types.NullObject value) {
            this.requestDenied = value;
        }

        
        public void selectRequestDenied () {
            selectRequestDenied (new org.bn.types.NullObject());
	}
	
        public void selectRequestDenied (org.bn.types.NullObject value) {
            this.requestDenied = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUndefinedReason () {
            return this.undefinedReason;
        }

        public boolean isUndefinedReasonSelected () {
            return this.undefinedReason != null;
        }

        private void setUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
        }

        
        public void selectUndefinedReason () {
            selectUndefinedReason (new org.bn.types.NullObject());
	}
	
        public void selectUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getCallerNotRegistered () {
            return this.callerNotRegistered;
        }

        public boolean isCallerNotRegisteredSelected () {
            return this.callerNotRegistered != null;
        }

        private void setCallerNotRegistered (org.bn.types.NullObject value) {
            this.callerNotRegistered = value;
        }

        
        public void selectCallerNotRegistered () {
            selectCallerNotRegistered (new org.bn.types.NullObject());
	}
	
        public void selectCallerNotRegistered (org.bn.types.NullObject value) {
            this.callerNotRegistered = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getRouteCallToGatekeeper () {
            return this.routeCallToGatekeeper;
        }

        public boolean isRouteCallToGatekeeperSelected () {
            return this.routeCallToGatekeeper != null;
        }

        private void setRouteCallToGatekeeper (org.bn.types.NullObject value) {
            this.routeCallToGatekeeper = value;
        }

        
        public void selectRouteCallToGatekeeper () {
            selectRouteCallToGatekeeper (new org.bn.types.NullObject());
	}
	
        public void selectRouteCallToGatekeeper (org.bn.types.NullObject value) {
            this.routeCallToGatekeeper = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setInvalidEndpointIdentifier(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getInvalidEndpointIdentifier () {
            return this.invalidEndpointIdentifier;
        }

        public boolean isInvalidEndpointIdentifierSelected () {
            return this.invalidEndpointIdentifier != null;
        }

        private void setInvalidEndpointIdentifier (org.bn.types.NullObject value) {
            this.invalidEndpointIdentifier = value;
        }

        
        public void selectInvalidEndpointIdentifier () {
            selectInvalidEndpointIdentifier (new org.bn.types.NullObject());
	}
	
        public void selectInvalidEndpointIdentifier (org.bn.types.NullObject value) {
            this.invalidEndpointIdentifier = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setResourceUnavailable(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getResourceUnavailable () {
            return this.resourceUnavailable;
        }

        public boolean isResourceUnavailableSelected () {
            return this.resourceUnavailable != null;
        }

        private void setResourceUnavailable (org.bn.types.NullObject value) {
            this.resourceUnavailable = value;
        }

        
        public void selectResourceUnavailable () {
            selectResourceUnavailable (new org.bn.types.NullObject());
	}
	
        public void selectResourceUnavailable (org.bn.types.NullObject value) {
            this.resourceUnavailable = value;
            
                    setCalledPartyNotRegistered(null);
                
                    setInvalidPermission(null);
                
                    setRequestDenied(null);
                
                    setUndefinedReason(null);
                
                    setCallerNotRegistered(null);
                
                    setRouteCallToGatekeeper(null);
                
                    setInvalidEndpointIdentifier(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AdmissionRejectReason.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            