
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "CallModel" )
    public class CallModel implements IASN1PreparedElement {
            
        @ASN1Null ( name = "direct" ) 
    
        @ASN1Element ( name = "direct", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject direct = null;
                
  
        @ASN1Null ( name = "gatekeeperRouted" ) 
    
        @ASN1Element ( name = "gatekeeperRouted", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject gatekeeperRouted = null;
                
  
        
        public org.bn.types.NullObject getDirect () {
            return this.direct;
        }

        public boolean isDirectSelected () {
            return this.direct != null;
        }

        private void setDirect (org.bn.types.NullObject value) {
            this.direct = value;
        }

        
        public void selectDirect () {
            selectDirect (new org.bn.types.NullObject());
	}
	
        public void selectDirect (org.bn.types.NullObject value) {
            this.direct = value;
            
                    setGatekeeperRouted(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getGatekeeperRouted () {
            return this.gatekeeperRouted;
        }

        public boolean isGatekeeperRoutedSelected () {
            return this.gatekeeperRouted != null;
        }

        private void setGatekeeperRouted (org.bn.types.NullObject value) {
            this.gatekeeperRouted = value;
        }

        
        public void selectGatekeeperRouted () {
            selectGatekeeperRouted (new org.bn.types.NullObject());
	}
	
        public void selectGatekeeperRouted (org.bn.types.NullObject value) {
            this.gatekeeperRouted = value;
            
                    setDirect(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CallModel.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            