
package asn1;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TestSimpleSequence", isSet = false )
    public class TestSimpleSequence implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "field1", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Long field1 = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "field2", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private String field2 = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "field3", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private String field3 = null;
                
  
        
        public Long getField1 () {
            return this.field1;
        }

        

        public void setField1 (Long value) {
            this.field1 = value;
        }
        
  
        
        public String getField2 () {
            return this.field2;
        }

        

        public void setField2 (String value) {
            this.field2 = value;
        }
        
  
        
        public String getField3 () {
            return this.field3;
        }

        

        public void setField3 (String value) {
            this.field3 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestSimpleSequence.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            