
package h225;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "ReleaseCompleteReason" )
    public class ReleaseCompleteReason implements IASN1PreparedElement {
            
        @ASN1Null ( name = "noBandwidth" ) 
    
        @ASN1Element ( name = "noBandwidth", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject noBandwidth = null;
                
  
        @ASN1Null ( name = "gatekeeperResources" ) 
    
        @ASN1Element ( name = "gatekeeperResources", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject gatekeeperResources = null;
                
  
        @ASN1Null ( name = "unreachableDestination" ) 
    
        @ASN1Element ( name = "unreachableDestination", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject unreachableDestination = null;
                
  
        @ASN1Null ( name = "destinationRejection" ) 
    
        @ASN1Element ( name = "destinationRejection", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject destinationRejection = null;
                
  
        @ASN1Null ( name = "invalidRevision" ) 
    
        @ASN1Element ( name = "invalidRevision", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject invalidRevision = null;
                
  
        @ASN1Null ( name = "noPermission" ) 
    
        @ASN1Element ( name = "noPermission", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject noPermission = null;
                
  
        @ASN1Null ( name = "unreachableGatekeeper" ) 
    
        @ASN1Element ( name = "unreachableGatekeeper", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject unreachableGatekeeper = null;
                
  
        @ASN1Null ( name = "gatewayResources" ) 
    
        @ASN1Element ( name = "gatewayResources", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject gatewayResources = null;
                
  
        @ASN1Null ( name = "badFormatAddress" ) 
    
        @ASN1Element ( name = "badFormatAddress", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject badFormatAddress = null;
                
  
        @ASN1Null ( name = "adaptiveBusy" ) 
    
        @ASN1Element ( name = "adaptiveBusy", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject adaptiveBusy = null;
                
  
        @ASN1Null ( name = "inConf" ) 
    
        @ASN1Element ( name = "inConf", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject inConf = null;
                
  
        @ASN1Null ( name = "undefinedReason" ) 
    
        @ASN1Element ( name = "undefinedReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject undefinedReason = null;
                
  
        @ASN1Null ( name = "facilityCallDeflection" ) 
    
        @ASN1Element ( name = "facilityCallDeflection", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject facilityCallDeflection = null;
                
  
        
        public org.bn.types.NullObject getNoBandwidth () {
            return this.noBandwidth;
        }

        public boolean isNoBandwidthSelected () {
            return this.noBandwidth != null;
        }

        private void setNoBandwidth (org.bn.types.NullObject value) {
            this.noBandwidth = value;
        }

        
        public void selectNoBandwidth () {
            selectNoBandwidth (new org.bn.types.NullObject());
	}
	
        public void selectNoBandwidth (org.bn.types.NullObject value) {
            this.noBandwidth = value;
            
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getGatekeeperResources () {
            return this.gatekeeperResources;
        }

        public boolean isGatekeeperResourcesSelected () {
            return this.gatekeeperResources != null;
        }

        private void setGatekeeperResources (org.bn.types.NullObject value) {
            this.gatekeeperResources = value;
        }

        
        public void selectGatekeeperResources () {
            selectGatekeeperResources (new org.bn.types.NullObject());
	}
	
        public void selectGatekeeperResources (org.bn.types.NullObject value) {
            this.gatekeeperResources = value;
            
                    setNoBandwidth(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUnreachableDestination () {
            return this.unreachableDestination;
        }

        public boolean isUnreachableDestinationSelected () {
            return this.unreachableDestination != null;
        }

        private void setUnreachableDestination (org.bn.types.NullObject value) {
            this.unreachableDestination = value;
        }

        
        public void selectUnreachableDestination () {
            selectUnreachableDestination (new org.bn.types.NullObject());
	}
	
        public void selectUnreachableDestination (org.bn.types.NullObject value) {
            this.unreachableDestination = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getDestinationRejection () {
            return this.destinationRejection;
        }

        public boolean isDestinationRejectionSelected () {
            return this.destinationRejection != null;
        }

        private void setDestinationRejection (org.bn.types.NullObject value) {
            this.destinationRejection = value;
        }

        
        public void selectDestinationRejection () {
            selectDestinationRejection (new org.bn.types.NullObject());
	}
	
        public void selectDestinationRejection (org.bn.types.NullObject value) {
            this.destinationRejection = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getInvalidRevision () {
            return this.invalidRevision;
        }

        public boolean isInvalidRevisionSelected () {
            return this.invalidRevision != null;
        }

        private void setInvalidRevision (org.bn.types.NullObject value) {
            this.invalidRevision = value;
        }

        
        public void selectInvalidRevision () {
            selectInvalidRevision (new org.bn.types.NullObject());
	}
	
        public void selectInvalidRevision (org.bn.types.NullObject value) {
            this.invalidRevision = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getNoPermission () {
            return this.noPermission;
        }

        public boolean isNoPermissionSelected () {
            return this.noPermission != null;
        }

        private void setNoPermission (org.bn.types.NullObject value) {
            this.noPermission = value;
        }

        
        public void selectNoPermission () {
            selectNoPermission (new org.bn.types.NullObject());
	}
	
        public void selectNoPermission (org.bn.types.NullObject value) {
            this.noPermission = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUnreachableGatekeeper () {
            return this.unreachableGatekeeper;
        }

        public boolean isUnreachableGatekeeperSelected () {
            return this.unreachableGatekeeper != null;
        }

        private void setUnreachableGatekeeper (org.bn.types.NullObject value) {
            this.unreachableGatekeeper = value;
        }

        
        public void selectUnreachableGatekeeper () {
            selectUnreachableGatekeeper (new org.bn.types.NullObject());
	}
	
        public void selectUnreachableGatekeeper (org.bn.types.NullObject value) {
            this.unreachableGatekeeper = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getGatewayResources () {
            return this.gatewayResources;
        }

        public boolean isGatewayResourcesSelected () {
            return this.gatewayResources != null;
        }

        private void setGatewayResources (org.bn.types.NullObject value) {
            this.gatewayResources = value;
        }

        
        public void selectGatewayResources () {
            selectGatewayResources (new org.bn.types.NullObject());
	}
	
        public void selectGatewayResources (org.bn.types.NullObject value) {
            this.gatewayResources = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getBadFormatAddress () {
            return this.badFormatAddress;
        }

        public boolean isBadFormatAddressSelected () {
            return this.badFormatAddress != null;
        }

        private void setBadFormatAddress (org.bn.types.NullObject value) {
            this.badFormatAddress = value;
        }

        
        public void selectBadFormatAddress () {
            selectBadFormatAddress (new org.bn.types.NullObject());
	}
	
        public void selectBadFormatAddress (org.bn.types.NullObject value) {
            this.badFormatAddress = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getAdaptiveBusy () {
            return this.adaptiveBusy;
        }

        public boolean isAdaptiveBusySelected () {
            return this.adaptiveBusy != null;
        }

        private void setAdaptiveBusy (org.bn.types.NullObject value) {
            this.adaptiveBusy = value;
        }

        
        public void selectAdaptiveBusy () {
            selectAdaptiveBusy (new org.bn.types.NullObject());
	}
	
        public void selectAdaptiveBusy (org.bn.types.NullObject value) {
            this.adaptiveBusy = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getInConf () {
            return this.inConf;
        }

        public boolean isInConfSelected () {
            return this.inConf != null;
        }

        private void setInConf (org.bn.types.NullObject value) {
            this.inConf = value;
        }

        
        public void selectInConf () {
            selectInConf (new org.bn.types.NullObject());
	}
	
        public void selectInConf (org.bn.types.NullObject value) {
            this.inConf = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setUndefinedReason(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUndefinedReason () {
            return this.undefinedReason;
        }

        public boolean isUndefinedReasonSelected () {
            return this.undefinedReason != null;
        }

        private void setUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
        }

        
        public void selectUndefinedReason () {
            selectUndefinedReason (new org.bn.types.NullObject());
	}
	
        public void selectUndefinedReason (org.bn.types.NullObject value) {
            this.undefinedReason = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setFacilityCallDeflection(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getFacilityCallDeflection () {
            return this.facilityCallDeflection;
        }

        public boolean isFacilityCallDeflectionSelected () {
            return this.facilityCallDeflection != null;
        }

        private void setFacilityCallDeflection (org.bn.types.NullObject value) {
            this.facilityCallDeflection = value;
        }

        
        public void selectFacilityCallDeflection () {
            selectFacilityCallDeflection (new org.bn.types.NullObject());
	}
	
        public void selectFacilityCallDeflection (org.bn.types.NullObject value) {
            this.facilityCallDeflection = value;
            
                    setNoBandwidth(null);
                
                    setGatekeeperResources(null);
                
                    setUnreachableDestination(null);
                
                    setDestinationRejection(null);
                
                    setInvalidRevision(null);
                
                    setNoPermission(null);
                
                    setUnreachableGatekeeper(null);
                
                    setGatewayResources(null);
                
                    setBadFormatAddress(null);
                
                    setAdaptiveBusy(null);
                
                    setInConf(null);
                
                    setUndefinedReason(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ReleaseCompleteReason.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            