/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Line.java
 *
 * Created on 11 nov. 2011, 19:43:44
 */
package com.devoteam.srit.xmlloader.gui.better;

/**
 *
 * @author Gwenhael
 */
public class TestcaseLineView extends javax.swing.JPanel {

    /** Creates new form Line */
    public TestcaseLineView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBoxSelected = new javax.swing.JCheckBox();
        jSpinnerNumber = new javax.swing.JSpinner();
        jButtonAction = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jLabelIcon = new javax.swing.JLabel();
        jCheckBoxLogs = new javax.swing.JCheckBox();
        jButtonEdit = new javax.swing.JButton();
        jButtonProfile = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jCheckBoxSelected.setText("Testcase description or name");
        jCheckBoxSelected.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jCheckBoxSelected, gridBagConstraints);

        jSpinnerNumber.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinnerNumber.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jSpinnerNumber, gridBagConstraints);

        jButtonAction.setText("Start");
        jButtonAction.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonAction.setPreferredSize(new java.awt.Dimension(58, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonAction, gridBagConstraints);

        jProgressBar.setValue(35);
        jProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jProgressBar, gridBagConstraints);

        jLabelIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jLabelIcon, gridBagConstraints);

        jCheckBoxLogs.setText("Logs");
        jCheckBoxLogs.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jCheckBoxLogs, gridBagConstraints);

        jButtonEdit.setText("Edit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonEdit, gridBagConstraints);

        jButtonProfile.setText("Profile");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        add(jButtonProfile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonAction;
    protected javax.swing.JButton jButtonEdit;
    protected javax.swing.JButton jButtonProfile;
    protected javax.swing.JCheckBox jCheckBoxLogs;
    protected javax.swing.JCheckBox jCheckBoxSelected;
    protected javax.swing.JLabel jLabelIcon;
    protected javax.swing.JProgressBar jProgressBar;
    protected javax.swing.JSpinner jSpinnerNumber;
    // End of variables declaration//GEN-END:variables
}
